name: Deploy Storybook

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - name: Build
        working-directory: ../
        run: npm i && npm run build
      
      - name: Deploy
        working-directory: ../
        run: npm run deploy-storybook
